server.port: 8083

spring:
  datasource:
    url: jdbc:mysql://${DB_MYSQL_HOST}:${DB_MYSQL_PORT}/saga_microservice
    username: ${DB_MYSQL_USERNAME}
    password: ${DB_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    stream:
      function:
        definition: paymentProcessor
      bindings:
        paymentProcessor-in-0:
          destination: order-event
        paymentProcessor-out-0:
          destination: payment-event